### ISSUE TITLE
Display issues with jobs of type "admin"

### ISSUE THREAD

**Issue by waa** [domenkozar/almir#5]
An Admin type job does not have a level (Full, incremental, Differential) 

In several locations where Jobs are listed (Dashboard and Jobs list on Jobs page)  lots of "=" characters are used for the "Level" column which causes the column to be very wide and the page to be too big to fit on screen.

This causes web browser side-scroller to be displayed, and you need to scroll right to see the Priority, Scheduled, and Volume columns. 

This is true on both the  on the Jobs page   and   the Dashboard page - maybe others. Not sure yet.

Fix: Jobs of type Admin should have "None" or "N/A" or "Admin" for the Level

Additionally, Admin Jobs also show Volume of "Incremental" which makes no sense and I believe this, and the many "=" characters are probably just a a parsing issue since there is no actual Level for Admin jobs. 
## 

Bill Arlofski

**Comment by domenkozar** [comment]
This should also be fixed with #4

**Comment by waa** [comment]
This problem still exists in current version updated last night. 

This might not display correctly, but here is what the line in the Dashboard looks like:

UpdateSlots Admin   =================================================================================== 8   18-Apr-12 20:30 Incremental

**Comment by domenkozar** [comment]
Can you make a screenshot? That would help :)

**Comment by waa** [comment]
Yep... 

http://www.revpol.com/images/almir-dashboardAdminJobLevelEqualSigns-20120418.png

**Comment by domenkozar** [comment]
Can you paste somewhere output of this command in bconsole: 

.status dir scheduled

**Comment by waa** [comment]
Yep... It looks like due to to the fact that an "Admin" type job has no level, AND my Admin job is FIRST nightly, I think you are parsing the header line that is the "==================================================="  and using that as the Admin job's "level"   See below:

*.status dir scheduled

Scheduled Jobs:

# Level          Type     Pri  Scheduled          Name               Volume

```
           Admin      8  18-Apr-12 20:30    UpdateSlots        
```

Incremental    Backup    10  18-Apr-12 20:30    NewbyFull          c0_0006_0063
Incremental    Backup    10  18-Apr-12 20:30    SpeedyMusic        c0_0006_0063
Incremental    Backup    10  18-Apr-12 20:30    SpeedyFull         c0_0006_0063
Incremental    Backup    10  18-Apr-12 20:30    Voip               c0_0006_0063
Incremental    Backup    10  18-Apr-12 20:30    Fog                c0_0006_0063
Incremental    Backup    10  18-Apr-12 20:30    Satch              c0_0006_0063
Incremental    Backup    10  18-Apr-12 20:30    Admin              c0_0006_0063
Full           Backup    10  19-Apr-12 02:45    Zimbra             c0_0006_0063
Full           Backup    10  19-Apr-12 02:45    Helpdesk           c0_0006_0063
Full           Backup    11  19-Apr-12 02:45    Newby_MustHave     FT-MH_0022
Incremental    Backup    12  19-Apr-12 02:45    Catalog            c0_0006_0063
Full           Copy      15  19-Apr-12 03:00    CopyZimbra  
Full           Copy      15  19-Apr-12 03:00    CopyHelpdesk  
Full           Copy      15  19-Apr-12 03:00    CopyVoip  
Full           Copy      15  19-Apr-12 03:00    CopyCatalog

**Comment by waa** [comment]
Hmmm the paste did not work. 

I'll do another snapshot

here: http://www.revpol.com/images/almir-dashboardAdminJobLevelEqualSigns-20120418a.png

**Comment by domenkozar** [comment]
Great, this needs more thinking how to parse :) Thanks for the report!

**Comment by waa** [comment]
No problem... That's what beta testers are for  :)

Also don't forget what I also reported in the opening message of this ticket:

--[snip]--
"Additionally, Admin Jobs also show Volume of "Incremental" which makes no sense and I believe this, and the many "=" characters are probably just a a parsing issue since there is no actual Level for Admin jobs."
--[snip]--
